# -*- coding: utf-8 -*-
"""inventory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itJWq8kg2WvbQSaIS1PgouN__GVTICmC
"""



# Initialize data structures
item_names = []
item_prices = {}

def add_item():
    """Adds a new item and its price to the inventory."""
    while True:
        name = input("Enter item name: ").strip()
        if not name:
            print("Item name cannot be empty. Please try again.")
        elif name.lower() in [n.lower() for n in item_names]:
            print("This item name already exists. Please enter a unique name.")
        else:
            break

    while True:
        try:
            price = float(input("Enter price: "))
            if price < 0:
                print("Price cannot be negative. Please enter a valid price.")
            else:
                break
        except ValueError:
            print("Invalid price. Please enter a number.")

    item_names.append(name)
    item_prices[name] = price
    print("Item added successfully!\n")

def update_price():
    """Updates the price of an existing item."""
    name_to_update = input("Enter item name to update: ").strip()
    if name_to_update in item_prices:
        while True:
            try:
                new_price = float(input("Enter new price: "))
                if new_price < 0:
                    print("New price cannot be negative. Please enter a valid price.")
                else:
                    break
            except ValueError:
                print("Invalid price. Please enter a number.")
        item_prices[name_to_update] = new_price
        print("Price updated successfully!\n")
    else:
        print("Item not found in the inventory.\n")

def display_menu():
    """Displays the main menu options."""
    print("===== INVENTORY MENU =====")
    print("[1] Add Item")
    print("[2] Update Price")
    print("[3] Exit")

# Main program loop
while True:
    display_menu()
    choice = input("Choice: ").strip()

    if choice == '1':
        add_item()
    elif choice == '2':
        update_price()
    elif choice == '3':
        print("Exiting system...")
        break
    else:
        print("Invalid choice. Please select 1, 2, or 3.\n")

print("Current Inventory:")
if item_names:
    for name in item_names:
        print(f"  Item: {name}, Price: ${item_prices[name]:.2f}")
else:
    print("  Inventory is empty.")